import type { Metadata } from "next";
import "./globals.css";
import { dmSans } from "./fonts";
import { SpeedInsights } from "@vercel/speed-insights/next"

export const metadata: Metadata = {
  title: "Palia Scheduler",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${dmSans.className} antialiased`}
      >
        <SpeedInsights />
        {children}
      </body>
    </html>
  );
}
